apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000
---
apiVersion: v1
kind: Pod
metadata:
    name: flask-app
    labels:
      app: flask-app
spec:
    containers:
    - name: flask-app
      image: odavies15/task2-app # Dockerhub
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: Password123