apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 3306
---
apiVersion: v1
kind: Pod
metadata:
    name: mysql
    labels:
      app: db
spec:
    containers:
    - name: mysql
      image: odavies15/task2-db # Dockerhub
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
        secretKeyRef:
          name: db-root-password
          key: password